### ISSUE TITLE
Remove excess whitespace or increase the size of font/icon/badges

### ISSUE THREAD

**Issue by AustinMorales09** [annacrabb/portfolio#1]
Portfolio looked great! As I resized some of the text/badges seemed a little small for the viewport. I think we can resolve the issue by either by reducing the whitespace in each section or by increasing the size of text/badges on the different viewports.

**Comment by annacrabb** [comment]
Added some text to fill up the white space, and increased the smallest font size from 1rem to 1.2rem on screens 992px and larger
